# Generated by Django 6.0 on 2026-01-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_person_phone',
            new_name='mobile_phone',
        ),
    ]
