# Generated by Django 6.0 on 2026-01-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_contact_person_phone_client_mobile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mobile_phone',
            new_name='mobile_number',
        ),
    ]
