# Generated by Django 6.0 on 2026-01-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_assignment_status_work_status_alter_work_work_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workservice',
            name='add_document_names',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=150)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='master.workservice')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
