# Generated by Django 6.0 on 2026-01-09 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_remove_workservice_add_document_names_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='master.assignment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='master.document')),
            ],
            options={
                'db_table': 'assignment_document_submissions',
                'unique_together': {('assignment', 'document')},
            },
        ),
    ]
