# Generated by Django 6.0 on 2026-01-25 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_assignmentchatmessage_chatattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentdocumentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentdocumentsubmission',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignmentdocumentsubmission',
            unique_together={('assignment', 'document', 'employee')},
        ),
    ]
