# Generated by Django 6.0 on 2026-01-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_assignmentdocumentsubmission_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentdocumentsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentdocumentsubmission',
            name='work_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='master.workservice'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignmentdocumentsubmission',
            unique_together={('assignment', 'work_service', 'document', 'employee')},
        ),
    ]
