# Generated by Django 6.0 on 2026-01-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_assignmentdocumentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentchatmessage',
            name='work_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='master.workservice'),
        ),
    ]
