# Generated by Django 6.0 on 2026-02-17 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_employeedailyremark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_for_month',
            field=models.DateField(blank=True, help_text='The first day of the month this recurring work is for (e.g., 2024-01-01 for January 2024)', null=True),
        ),
        migrations.CreateModel(
            name='RecurringWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_mode', models.CharField(choices=[('Fixed', 'Fixed'), ('Reccuring', 'Reccuring')], max_length=10)),
                ('last_work_created_month', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employees', models.ManyToManyField(related_name='recurring_work_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_work_assignments', to='master.assignment')),
                ('work_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_assignments', to='master.workservice')),
            ],
            options={
                'db_table': 'recurring_work_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'work_service')},
            },
        ),
        migrations.AddField(
            model_name='work',
            name='recurring_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_works', to='master.recurringworkassignment'),
        ),
    ]
