# Generated by Django 6.0 on 2026-02-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_smsmessage_smslog'),
    ]

    operations = [
        # No-op migration: sent_at fields were never created in the database
    ]
