# Generated by Django 6.0 on 2026-02-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_remove_smslog_sent_at_remove_smsmessage_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='smsmessage',
            name='sent_at',
        ),
    ]
