"""
Django settings for ca_firm project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOMAIN_URL = "http://127.0.0.1:8000"  # or your live domain

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u!yj)-sk!hqlgq+fzei#a9)4*i5xa5a-yil4@z6lb*)x2bc^35'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'userauth',
    'master',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ca_firm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ca_firm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         #'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cadatabase',
#         'USER': 'root',
#         'PASSWORD': 'shinde',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'autocommit': True,
#         }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        #'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cadatabase',
        'USER': 'root',
        'PASSWORD': 'shinde',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'autocommit': True,
        }
    }
}

# DATABASES = {
#     'default': {
#         #'ENGINE': 'django.db.backends.mysql',
#         'ENGINE': 'mysql.connector.django',
#         'NAME': 'company_db',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '3307',
#         'OPTIONS': {
#             'autocommit': True,
#         }
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'userauth.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Email Configuration ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Replace with your actual email
# EMAIL_HOST_USER = 'prasadshindeking@gmail.com' 
EMAIL_HOST_USER = 'easymytask@gmail.com' 

# IMPORTANT: This is NOT your login password. 
# It must be a 16-digit "App Password" from Google.
# EMAIL_HOST_PASSWORD = 'qhadlkptaohzbchw' 

EMAIL_HOST_PASSWORD = 'dcpxyolcqdcxhzwh' 

# This appears as the sender name in the inbox
DEFAULT_FROM_EMAIL = 'Easy MY Task <easymytask@gmail.com>'

# ========== BHASHSMS WHATSAPP CONFIGURATION ==========
SMS_ENABLED = True
SMS_PROVIDER = 'bhashsms'
SMS_MOCK_MODE = False  # Set to False for live sending

# BhashSMS Settings
BHASHSMS_USER = 'ISC_BWAI'
BHASHSMS_PASS = '123456'
BHASHSMS_SENDER = 'BUZWAP'
BHASHSMS_PRIORITY = 'wa'
BHASHSMS_STYPE = 'normal'
BHASHSMS_DEFAULT_TEMPLATE = 'pdr_uti'
BHASHSMS_ACCEPTANCE_TEMPLATE = 'wa_uti'
BHASHSMS_COMPLETED_TEMPLATE = 'wcm_ibsc'
BHASHSMS_BULK_TEMPLATE = 'wa_bulk'
BHASHSMS_BIRTHDAY_TEMPLATE = 'wa_brt'
BHASHSMS_DEFAULT_PARAMS = '1,2'

# SMS Settings
SMS_BATCH_SIZE = 100
SMS_RETRY_COUNT = 3

# Birthday SMS Settings
BIRTHDAY_SMS_ENABLED = True
BIRTHDAY_SMS_TEMPLATE = "Happy Birthday! Thanks for being with us. Wishing you a wonderful day ahead. - CA Firm"

# SMS Logging
SMS_LOG_ENABLED = True
